const LOAD_PRODUCTS = 'LOAD_PRODUCTS';


const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'




export default {
    LOAD_PRODUCTS,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    UPDATE_CART_ITEM,
}